# This file was generated by GoReleaser. DO NOT EDIT.
cask "brewmaster" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "fbb010b75138964e9d09d6c269d1e7a051430144406cf916fbddd726baa6d0d6"
      url "https://github.com/patrickserrano/brewmaster/releases/download/v#{version}/brewmaster_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f5a46fa056cb20399b2063d1cb3d518605d199948c3cbb0a9374fb16dd7b2c5a"
      url "https://github.com/patrickserrano/brewmaster/releases/download/v#{version}/brewmaster_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "brewmaster"
  desc "Audit installed macOS apps and adopt them into Homebrew"
  homepage "https://github.com/patrickserrano/brewmaster"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "brewmaster"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/brewmaster"],
        sudo: false
    end
  end

  # No zap stanza required

end
